EXEC = $(basename $(wildcard *.cpp) $(wildcard *.cu))

include Makefile.inc

# Extra dependencies for executables

test.o: INCLUDES += -I../cublas_batch_gemm
test: LDLIBS += -lcublas

tucker_decomp_kernel.o: INCLUDES += -I/home/yang/btas_test_2
tucker_decomp_kernel: LDLIBS += -lcublas -I/home/yang/btas_test_2
